# Generated by Django 5.2 on 2025-05-04 04:10

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country', 'region', 'city', 'street'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='alumni',
            name='engagement_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumni',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='degree',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='faculty_id',
            field=models.CharField(db_index=True, help_text='Unique faculty identification number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='position',
            field=models.CharField(choices=[('professor', 'Professor'), ('assoc_professor', 'Associate Professor'), ('asst_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('instructor', 'Instructor'), ('adjunct', 'Adjunct Faculty'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty Member'), ('staff', 'Administrative Staff'), ('admin', 'Administrator'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='staff_id',
            field=models.CharField(db_index=True, help_text='Unique staff identification number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average (0.00 - 4.00)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='accounts_ad_city_a5f6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'region'], name='accounts_ad_country_a22b89_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['graduation_year'], name='accounts_al_graduat_043d64_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['degree'], name='accounts_al_degree_c2f4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['is_donor'], name='accounts_al_is_dono_25878d_idx'),
        ),
        migrations.AddIndex(
            model_name='facultymember',
            index=models.Index(fields=['department', 'position'], name='accounts_fa_departm_e9acd5_idx'),
        ),
        migrations.AddIndex(
            model_name='facultymember',
            index=models.Index(fields=['hire_date'], name='accounts_fa_hire_da_d313dc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_type', 'is_active'], name='accounts_pr_user_ty_30a287_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_joined'], name='accounts_pr_date_jo_cbd6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['department'], name='accounts_st_departm_4b5e73_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['hire_date'], name='accounts_st_hire_da_e92e44_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['admin_level'], name='accounts_st_admin_l_13e41a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_status'], name='accounts_st_academi_322056_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_date'], name='accounts_st_enrollm_d0ef35_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['gpa'], name='accounts_st_gpa_c78941_idx'),
        ),
    ]
