# Generated by Django 5.2 on 2025-04-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
    ]
